language: node_js
node_js: 
    - '11'
install:
  - npm install
after_script:
  - cd ./dist
  - git init
  - git config user.name "Deivo"
  - git config user.email "zq.dream@163.com"
  - git add -A
  - git commit -m "Update documents"
  - git push --force  "https://${GH_TOKEN}@${GH_REF}" "master:gh-pages"